version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/data
    command: sqlite3 /data/database.db < /docker-entrypoint-initdb.d/init.sql
