version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/data
    command: sqlite3 /data/database.db < /docker-entrypoint-initdb.d/init.sql

  django:
    build:
      context: ./django-app  # Specify the relative path to the Django app directory
      dockerfile: Dockerfile  # Reference the Dockerfile inside the Django app directory
    volumes:
      - ./django-app:/app  # Mount the Django app directory
    ports:
      - 8000:8000  # Expose port 8000 for the Django app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000  # Replace with your Django command